version: '3'

services:
  app:
    build: ./
    restart: always
    volumes:
      - ./:/app
    depends_on:
      - mysql
      - redis

  queue:
    build: ./
    command: 'if [$APP_ENV == "local"]; then php artisan queue:listen; else php artisan queue:work; fi'
    restart: always
    volumes:
      - ./:/app
    depends_on:
      - mysql
      - redis

  scheduler:
    build: ./
    command: 'while true; do php artisan schedule:run; sleep 60; done'
    restart: always
    volumes:
      - ./:/app
    depends_on:
      - mysql
      - redis

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    ports:
      - "80:80"

  mysql:
    image: mysql:8
    restart: always
    environment:
      - "MYSQL_RANDOM_ROOT_PASSWORD=1"
      - "MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-}"
      - "MYSQL_DATABASE=${DB_DATABASE}"
      - "MYSQL_USER=${DB_USERNAME}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
    command:
      - "--default-authentication-plugin=mysql_native_password"
    volumes:
     - dotto_mysql:/var/lib/mysql

  redis:
    image: redis
    volumes:
     - dotto_redis:/data

volumes:
  dotto_mysql:
  dotto_redis:
